### ISSUE TITLE
ipad sender?

### ISSUE THREAD

**Issue by mechpil0t** [keijiro/Rcam2#1]
would it be possible to have a few notes about how to send from ipad?

for example in this which unity project in this repo do we use to send the data from the ipad?
or do we use the old KladNDI?
I noticed the only project with ARfoundation was the RcamController however when i build and try to run i get the following Linker command error in xcode:
`directory not found for option '-L/Library/NDI SDK for Applielib/iOS'
`

**Comment by keijiro** [comment]
You need the NDI SDK 4.5 to build the controller app (sender). See README on KalkNDI for details: https://github.com/keijiro/KlakNDI
