### ISSUE TITLE
data of body skeleton?

### ISSUE THREAD

**Issue by xxxhhhyxy** [keijiro/Rcam2#10]
Hi, I am so impressed by the particle effects you applied to the real-time video stream, on the human body.
but here I have a very simple question, and I will be very grateful if you can answer:
I guess you get the LiDAR first to extract the contour of the DJ player, then render his body shape in the video, because that is the simplest way. So my question is, have you ever tried to extract the body pose of the DJ player based on the LiDAR data? a.k.a. the exact positions of the body joints (wrist, elbow, and shoulder)?

**Comment by keijiro** [comment]
> So my question is, have you ever tried to extract the body pose of the DJ player based on the LiDAR data?

The short answer is no. I think you can use AR Kit to estimate the pose, but I have never used it in that way.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
