### ISSUE TITLE
Running into Unity Cloud Build errors

### ISSUE THREAD

**Issue by thePostFuturist** [keijiro/Rcam2#13]
Updated the NDI plugin through the package manager and copied over the Runtime directory, but running into this on Cloud Build:

5512: [2022-12-11T04:25:29.632Z] - 7.2.3.2.4.2 - INFO: ⚠;️  ld: directory not found for option '-L/Library/NDI SDK for Apple/lib/iOS'

5516: [2022-12-11T04:25:29.632Z] - 7.2.3.2.4.2 - INFO: ❌;  ld: library not found for -lndi_ios

5524: [2022-12-11T04:25:29.632Z] - 7.2.3.2.4.2 - INFO: ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Not seeing this directory in my local Library if I try to build on Windows either, what am I missing that generates it?

**Comment by keijiro** [comment]
As noted on README, you have to install the NDI SDK for iOS builds.

**Comment by keijiro** [comment]
I'm closing this issue as answered. Please reopen it for further problems.
