### ISSUE TITLE
Library ndi_ios cannot be found. Any way to download sdk or build it without ndi sdk 4.5?

### ISSUE THREAD

**Issue by brainslun** [keijiro/Rcam2#15]
![unnamed](https://github.com/user-attachments/assets/d58e1817-0682-4dab-86ae-e4ef542fb55e)

Hi,

I am trying to build this in 2024 on my ipad. But there is no ios ndi sdk online anymore. Tried ndi tools for mac still no luck..

Is there any way to get this project running in 2024?

Thanks

**Comment by keijiro** [comment]
You can still download the NDI SDK for "MacOS / iOS" from their site (you have to fill a form to get a link for it).

**Comment by brainslun** [comment]
Hi Keijiro, I did fill the form and they are no longer offering NDI SDK for IOS/Mac. I did a pretty thorough research online to find ndi sdk 4.5 archived elsewhere but did not find any. I am pretty sure that NDI has stopped supporting ios/mac since it's also what chatgpt answered.

Is there anyway I can bypass using it or get it to build?
![ndisdk](https://github.com/user-attachments/assets/0adfdf2d-39a7-4c5e-adf9-2cd49c9fa4f7)

**Comment by keijiro** [comment]
That’s strange—I tried filling out the form again and received an email like the one shown in the attached image.

<img width="595" alt="Screenshot 2024-11-09 at 11 12 26 AM" src="https://github.com/user-attachments/assets/88eb8181-0cce-4a07-bc18-9c9c6ced2f56">

Could you try submitting the form again with different answers? It’s possible that the links provided vary based on the responses.
