### ISSUE TITLE
NDI Receiver not seeing device

### ISSUE THREAD

**Issue by thesoulharmonic** [keijiro/Rcam2#2]
I'm trying to connect an iPad Pro 2020 Gen 4 but the Receiver is only showing me my Desktop as an input in 'Ndi name', I've tried over-typing it to my device name but nothing shows up.

I'm seeing the iPad output in the NDI Monitor but not in Unity. I'm on Unity 2020.1.6f1, NDI SDK 4.5 and Windows 10

Running iOS 14 on the iPad.

Any advice on the basic setup would be great. Thank you

**Comment by keijiro** [comment]
- Turn off the Windows firewall.
- Make sure that your iPad and your PC are connected to the same network.
- Turn off unrelated networks (for example, if you're using a wired connection, turn off WiFi).
- If you're using WSL2, turn off the vEthernet: https://twitter.com/_kzr/status/1301722460421644289

**Comment by thesoulharmonic** [comment]
Ah great! it was the firewall! Thank you, amazing work as usual 👍

**Comment by keijiro** [comment]
Okay. I'll add it to the FAQ.
