### ISSUE TITLE
works fine on a 2018 iPad Pro 12.9"

### ISSUE THREAD

**Issue by AaronMeyers** [keijiro/Rcam2#3]
In case anyone was curious, this works really well on my 2018 iPad Pro without a LiDAR sensor.

**Comment by AaronMeyers** [comment]
Also works well on iPhone 11 Pro Max!

**Comment by keijiro** [comment]
Please check the FAQ on README.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by AaronMeyers** [comment]
ok yes... i spent a little more time with it today and now i see that the depth map doesn't work. i tried changing the iOS app to use the depth map from the human occlusion subsystem instead of the environment depth map and it doesn't have the precision to use with human-scale features. :(

i'll have to wait til i upgrade my device!

**Comment by keijiro** [comment]
> i tried changing the iOS app to use the depth map from the human occlusion subsystem instead of the environment depth map and it doesn't have the precision to use with human-scale features. :(

I tried it once too, and the conclusion was the same. The environment depth map from LiDAR is far better than the human occlusion depth map, it's still not the perfect option though (the resolution of LiDAR is quite low compared to other depth cameras like Kinect).
