### ISSUE TITLE
YouTube link in README is private

### ISSUE THREAD

**Issue by edorgeville** [keijiro/Rcam2#4]
![image](https://user-images.githubusercontent.com/2685884/94485904-9f16b400-01ac-11eb-8059-8d2215756f8d.png)

**Comment by keijiro** [comment]
Unfortunately, Boiler Room made it private for some reason (maybe license issue or something like that). I updated README to link to Vimeo instead.

**Comment by edorgeville** [comment]
Sweet! It looks awesome, thank you so much for open-sourcing your work!
