### ISSUE TITLE
It works, but it's too slow. need help .. 

### ISSUE THREAD

**Issue by minsoo5403** [keijiro/Rcam2#5]
The iPad Pro connects to Unity 2020.1.6 from Windows 10 but updates are very slow.

In the profiler window, can see that 100 to 200 frames are processed, but can it slow down due to network speed problems?

**Comment by keijiro** [comment]
See TIPS on README.md. A wired connection is recommended.

**Comment by minsoo5403** [comment]
Thank you. This project is excellent ~ !
