### ISSUE TITLE
Target Device of RCamcontroller defaults to iPad Only

### ISSUE THREAD

**Issue by mechpil0t** [keijiro/Rcam2#6]
not a big problem but a little annoying 
Target Device of the RCamcontroller project defaults to IPad only but this should be iPad + iPhone now the iPhone 12 has lidar

**Comment by keijiro** [comment]
I won't support iPhone 12 Pro because it needs lots of changes due to the aspect ratio difference. Please understand that this is just a one-off project for a one-night show.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
